spring:
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
server:
  port: 59258
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream